FROM ubuntu:latest
FROM openjdk:8
FROM mysql:latest
EXPOSE 3306

ADD ./my.cnf /etc/mysql/conf.d/custom.cnf

RUN apt-get update && apt-get dist-upgrade -y

#Utilities
RUN apt-get install -y net-tools wget curl sudo telnet nano openssh-server openssh-client bzip2 tar bc git iputils-ping mysql-client

RUN apt-get update && apt-get clean all





